services:

  worker:
    build:
      context: .
      target: prod
    env_file:
      - .env
    depends_on:
      temporal:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agent-temporal-network

  temporal:
    image: temporalio/auto-setup:1.25.2.0
    depends_on:
      temporal-postgresql:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
    networks:
      - agent-temporal-network
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "workflow", "list"]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - 7233:7233

  temporal-ui:
    image: temporalio/ui:2.31.2
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    ports:
      - 8080:8080
    networks:
      - agent-temporal-network

  temporal-postgresql:
    image: postgres:12.21
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agent-temporal-network

  redis:
    image: redis:7.0.11
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 10s
    networks:
      - agent-temporal-network

networks:
  agent-temporal-network:
    driver: bridge
    name: agent-temporal-network